In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
anime_csv_path = './anime.csv'
ratings_csv_path = './rating.csv'

In [3]:
anime_data = pd.read_csv(anime_csv_path)
anime_data['genre'].fillna('', inplace=True)
anime_data.head()

# Use this line to check for Nan genre value
# anime_data.iloc[2844]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [4]:
anime_data['genre_array'] = anime_data['genre'].str.split(', ')
anime_data.head()

,anime_id,name,genre,type,episodes,rating,members,genre_array
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,"[Drama, Romance, School, Supernatural]"
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,"[Action, Adventure, Drama, Fantasy, Magic, Mil..."
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,"[Action, Comedy, Historical, Parody, Samurai, ..."
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,"[Sci-Fi, Thriller]"
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,"[Action, Comedy, Historical, Parody, Samurai, ..."

In [5]:
for index, anime in anime_data.iterrows():   
    for genre in anime['genre_array']:
        if f'is_{genre}' not in anime_data.columns.tolist():
        
            anime_data[f'{genre}'] = anime_data['genre_array'].apply(
                lambda genre_array: 1 if genre in genre_array else 0
            )

anime_data.drop(columns=['genre_array'], inplace=True)
anime_data.head()

,anime_id,name,genre,type,episodes,rating,members,Drama,Romance,School,...,Game,Dementia,Harem,Cars,Kids,Shoujo Ai,,Hentai,Yaoi,Yuri
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,0,0,0,...,0,0,0,0,0,0,0,0,0,0